In [1]:
# 1. What is python library? why do we use python libraries ?

# Solution :
'''
A Python library is a collection of precompiled code—such as modules, functions, and classes—that can be reused
in your programs to perform specific tasks. Libraries are designed to make programming more efficient by allowing 
developers to avoid writing code from scratch for common operations. Instead, you can import and use existing, 
well-tested code from libraries to handle tasks ranging from mathematical computations and data analysis to web 
development and machine learning

use of Python libraries?

Efficiency and Productivity: Libraries provide ready-to-use code, saving developers time and effort by 
                            eliminating the need to reinvent the wheel for standard tasks.

Code Reusability: They allow you to reuse code across different projects, making your work more modular and maintainable.

Standardization and Reliability: Libraries are thoroughly tested and maintained by communities or organizations, 
                            ensuring reliability and reducing bugs in your code.

Access to Advanced Functionality: Libraries enable you to perform complex operations—such as data visualization, 
                            machine learning, or web development—with simple function calls, even if you are not an 
                            expert in those domains.

Community Support: Popular libraries have large communities, offering documentation, tutorials, and support, 
                            which helps in troubleshooting and learning.

Simplified Maintenance: Using libraries helps keep your codebase smaller and easier to maintain, as common functionalities
                            are handled by well-maintained external code
'''


'\nA Python library is a collection of precompiled code—such as modules, functions, and classes—that can be reused\nin your programs to perform specific tasks. Libraries are designed to make programming more efficient by allowing \ndevelopers to avoid writing code from scratch for common operations. Instead, you can import and use existing, \nwell-tested code from libraries to handle tasks ranging from mathematical computations and data analysis to web \ndevelopment and machine learning\n\nuse of Python libraries?\n\nEfficiency and Productivity: Libraries provide ready-to-use code, saving developers time and effort by \n                            eliminating the need to reinvent the wheel for standard tasks.\n\nCode Reusability: They allow you to reuse code across different projects, making your work more modular and maintainable.\n\nStandardization and Reliability: Libraries are thoroughly tested and maintained by communities or organizations, \n                            ensuring r

In [11]:
# 2. What is the difference between numpy array and list?

# Solution :
'''
Differences between Python Lists and NumPy Arrays
Data Type Flexibility
        Python List: Can store elements of different data types (e.g., integers, strings, objects).
        NumPy Array: All elements must be of the same data type (homogeneous).

Memory Efficiency
        Python List: Less memory efficient; each element is a separate object with metadata.
        NumPy Array: More memory efficient; data is stored in a contiguous block of memory.

Performance
        Python List: Slower for numerical operations.
        NumPy Array: Much faster for numerical computations due to vectorized operations.

Operations and Functionality
        Python List: Supports basic operations like append, insert, remove, etc.
        NumPy Array: Supports advanced mathematical operations, multi-dimensional slicing, and element-wise computations.

Resizing
        Python List: Can be resized dynamically (grow or shrink).
        NumPy Array: Fixed size; resizing creates a new array.

Use Cases
        Python List: Suitable for general-purpose data storage.
        NumPy Array: Ideal for numerical computations and handling large datasets.
'''


'\nDifferences between Python Lists and NumPy Arrays\nData Type Flexibility\n        Python List: Can store elements of different data types (e.g., integers, strings, objects).\n        NumPy Array: All elements must be of the same data type (homogeneous).\n\nMemory Efficiency\n        Python List: Less memory efficient; each element is a separate object with metadata.\n        NumPy Array: More memory efficient; data is stored in a contiguous block of memory.\n\nPerformance\n        Python List: Slower for numerical operations.\n        NumPy Array: Much faster for numerical computations due to vectorized operations.\n\nOperations and Functionality\n        Python List: Supports basic operations like append, insert, remove, etc.\n        NumPy Array: Supports advanced mathematical operations, multi-dimensional slicing, and element-wise computations.\n\nResizing\n        Python List: Can be resized dynamically (grow or shrink).\n        NumPy Array: Fixed size; resizing creates a new a

In [15]:
import numpy as np

In [3]:
# 3. find the shape, size and dimension of the following array?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''

# Solution
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)


Shape: (3, 4)
Size: 12
Dimension: 2


In [7]:
# 4. Write the python code to access the first row of the following array ?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''

# Solution :
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[0])

[1 2 3 4]


In [17]:
# 5. How to you access the element at the third row and fourth column from the given numpy array?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''

# Solution:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[2,3])


12


In [21]:
# 6. write code to extract all odd-indexed elements from the given numpy array?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''

# Solution :
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:, 1::2])


[[ 2  4]
 [ 6  8]
 [10 12]]


In [27]:
# 7. How can you generate a random 3 x 3 matrix with values between 0 and 1?

# Solution 

random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.02570817 0.38377122 0.80938044]
 [0.45677929 0.82641362 0.09987203]
 [0.56719159 0.49404166 0.97233686]]


In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?

# solution :
'''
1.
np.random.rand
    Distribution: Uniform distribution
    Range: Values are drawn uniformly between 0 (inclusive) and 1 (exclusive)
    Use case: When you want random numbers spread evenly across an interval.

Example:
        np.random.rand(3)

2.
np.random.randn
    Distribution: Standard normal (Gaussian) distribution
    Mean: 0
    Variance: 1
    Range: Values can be any real number, but most are clustered around 0, with some outliers.
    
Example:
    np.random.randn(3)  
'''


In [29]:
# 9. Write a code to increase the dimension of the following array?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''

# Solution :

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increase dimension: reshape to 3x4x1 (adds a third dimension)
arr_3d = arr.reshape(3, 4, 1)
print(arr_3d)






[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [33]:
# 10. How to transpose the following array in numpy?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''

# solution
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Using .T attribute
transposed_arr = arr.T
print("by using.T attribute")
print(transposed_arr)

# Or using the transpose function
transposed_arr = np.transpose(arr)
print("by using Transpose function")
print(transposed_arr)


by using.T attribute
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
by using Transpose function
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [41]:
# 11. Consider the following matrix.
matrix_a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
matrix_b = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
'''
Perform the following operation using python :
1. Index wise multiplication
2. Matrix Multiplication
3. Add both the matrics
4. Substract matrix B from A
5. Divide Matrix B by A
'''

# Solutions:

import numpy as np

matrix_a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix_b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 1. Index-wise (element-wise) multiplication
element_wise = matrix_a * matrix_b
print(" 1. Index wise multiplication ")
print(element_wise)

# 2. Matrix multiplication
matrix_mult = np.dot(matrix_a, matrix_b.T)
print(" 2. Matrix Multiplication ")
print(matrix_mult)

# 3. Addition
addition = matrix_a + matrix_b
print(" 3. Add both the matrics ")
print(addition)

# 4. Subtraction
subtraction = matrix_a - matrix_b
print(" 4. Substract matrix B from A ")
print(subtraction)

# 5. Division (element-wise)
division = np.divide(matrix_b, matrix_a)
print(" 5. Divide Matrix B by A ")
print(division)



 1. Index wise multiplication 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
 2. Matrix Multiplication 
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
 3. Add both the matrics 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
 4. Substract matrix B from A 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
 5. Divide Matrix B by A 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
# 12. Which function is numpy can be used to swap the byte order of an array?

# Solution
import numpy as np

arr = np.array([1, 256, 8755], dtype=np.int16)
arr_swapped = arr.byteswap()
print(arr_swapped)


[  256     1 13090]


In [ ]:
# 13. What is the significance of the np.linalg.inv function?

# Solutions
'''
The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix, 
a fundamental operation in linear algebra. Its significance lies in enabling solutions to systems of linear equations, 
statistical analyses, and machine learning algorithms.

Key Significance
Matrix Inversion:
    Computes the matrix A−1 such that A⋅A−1 =I, where I is the identity matrix.
    Essential for solving equations of the form Ax=B (solution: x=A−1B).

Square Matrix Requirement:
    Works only on square matrices (same rows and columns) with a non-zero determinant.

Error Handling:
    Raises LinAlgError if the matrix is singular (non-invertible) or not square.
'''

In [ ]:
# 14. What does the np.reshape function do, and how it is used?

# Solutions 
'''
The np.reshape function in NumPy is used to change the shape (dimensions) of an array without altering its data.
This means you can rearrange the elements of an array into a new configuration—for example, converting a 1D array 
into a 2D or 3D array, or flattening a multi-dimensional array into 1D.

Function Signature:
        numpy.reshape(a, newshape, order='C')
a: The array to be reshaped.
newshape: The desired shape as a tuple or integer.
order: Optional; determines the order in which elements are read/written ('C' for row-major, 'F' for column-major)

Usage Example:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = np.reshape(arr, (2, 3))
print(reshaped)


Key Features
    No Data Change: Only the shape (dimensions) of the array is changed, not the underlying data.
    Total Elements Must Match: The product of the new shape must equal the number of elements in the original array.
    Flexible Dimension: You can use -1 for one dimension, and NumPy will automatically calculate it.
    Order Parameter: Controls the order of element traversal during reshaping.

'''



In [45]:
# 15. What is broadcasting in numpy?

# Solutions.
'''
Broadcasting in NumPy is a powerful mechanism that allows arithmetic operations to be performed between 
arrays of different shapes and sizes, without explicitly reshaping or looping through data. When you operate on arrays, 
NumPy automatically expands the smaller array along certain dimensions so that its shape matches the larger array, 
enabling efficient, element-wise computations.

Key Features of Broadcasting:
    Automatic Shape Alignment: If two arrays have different shapes, NumPy tries to make them compatible by
    "stretching" the smaller array along dimensions of size 1 or missing dimensions.
    
    Efficiency: Broadcasting avoids unnecessary memory usage and loops, making operations faster and more memory-efficient.
    
    Rules: For broadcasting to work, the shapes of the arrays must be compatible—each dimension must be either equal in
    length or one of them must be 1.
'''
# Example 
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2,3)
b = np.array([10, 20, 30])             # shape (3,)
result = a + b
print(result)
# Output:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]
